site_name: 'RStudio Connect: rsconnect-python'

markdown_extensions:
  - toc:
      permalink: true
  - attr_list: {}
  - def_list: {}
  - tables: {}
  - admonition
  - pymdownx.superfences: {}
  - codehilite:
      guess_lang: false

plugins:
  - macros
  - search

nav:
  - index.md
  - changelog.md

theme:
  name: material
  logo: 'images/rstudio-logo.png'
  palette:
    primary: 'white'

extra_css:
  - css/custom.css

extra:
  rsconnect_python:
    version: !!python/object/apply:os.getenv ["VERSION"]
