name: snyk
on:
  schedule:
    - cron: "0 10 * * 1" # Monday @ 10am UTC
  workflow_dispatch:

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  SNYK_ORG: rstudio-connect

jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: snyk/actions/setup@master
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Run Snyk (setup.py)
        uses: snyk/actions/python@master
        with:
          command: monitor
          args: --file=setup.py --package-manager=pip --project-name=setup.py --org=${{ env.SNYK_ORG }}

      - name: Run Snyk (requirements.txt)
        uses: snyk/actions/python@master
        with:
          command: monitor
          args: --file=requirements.txt --package-manager=pip --project-name=requirements.txt --org=${{ env.SNYK_ORG }}
